# Please don't change this
version: 1

# Plugin messages
# Format: MiniMessage
# Documentation: https://docs.advntr.dev/minimessage/format.html
language:
  reload: "<gray>[<gradient:#5e4fa2:#f79459:red>Template</gradient>] Successfully reloaded!"
  version: "<gray>[<gradient:#5e4fa2:#f79459:red>Template</gradient>] Plugin version: "
  permission: "<red>You do not have permission to use this command."
  usage: "<white>Usage: /template <version/reload>"
